issues:
  exclude-rules:
    # Exclude `lll` issues for long lines with `go:generate`.
    - linters:
        - lll
      source: '^//go:generate '
    # Exclude funlen for testing files.
    - linters:
        - funlen
        - unparam
        - err113

      path: '(.+)_test\.go'

  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - errcheck
    - gofumpt
    - mnd
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - godot
    - revive
    - wsl
    - nlreturn
    - paralleltest
    - thelper
    - gocognit
    - govet
    - forcetypeassert
    - err113

linters-settings:
  govet:
    enable:
      - fieldalignment
      - shadow
  misspell:
    ignore-words:
      - 'intial'
  errcheck:
    exclude-functions:
      - github.com/hashicorp/terraform-plugin-testing/helper/schema:ForceNew|Set
      - fmt:.*
      - io:Close
  mnd:
    checks:
      - argument
    ignored-functions:
      - make
      - strconv.FormatFloat
      - strconv.FormatInt
      - strconv.ParseFloat
      - strconv.ParseInt
      - strings.SplitN
      - int64validator.OneOf
  nolintlint:
    require-explanation: true
    require-specific: true
    allow-no-explanation:
      - unparam
      - mnd
  paralleltest:
    ignore-missing: true

run:
  timeout: 35m
