---
version: "3.9"
services:
  sonarr:
    image: hotio/sonarr:release-4.0.12.2823@sha256:edc429a9964226fba754fee6c0daa46e8d3ff30dc00e73146995810152c6331f
    container_name: sonarr
    depends_on:
      - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./test.sh:/scripts/test.sh
      - ./config.xml:/config/config.xml
    ports:
      - 8989:8989
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/system/status"]
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 9091:9091