# Terraform Provider testing workflow.
name: CI

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
  push:
    branches:
      - main

jobs:
  ci:
    uses: devopsarr/shared-workflows/.github/workflows/terraform_provider_ci.yml@renovate/golangci-golangci-lint-action-6.x
    with:
      app-name: "SONARR"
      url: "http://localhost:8989"
    secrets: inherit