# Terraform Provider release workflow.
name: Release Management

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    branches:
      - main

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
#permissions:
#  contents: write

# Default values to simplify job configurations below.
env:
  # Go language version to use for building. This value should also be updated
  # in the testing workflow if changed.
  GO_VERSION: '1.17'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          token: ${{ secrets.GITHUB_TOKEN }}